#!/usr/bin/env python3
"""
File System Watcher for Personal AI Employee

Monitors the Drop/ folder and creates action files in Needs_Action/
when new files are detected.
"""

import os
import sys
import time
import yaml
from datetime import datetime
from pathlib import Path
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler


class DropEventHandler(FileSystemEventHandler):
    """Handler for file events in the Drop folder."""

    def __init__(self, vault_path, needs_action_path, logs_path):
        self.vault_path = Path(vault_path)
        self.needs_action_path = Path(needs_action_path)
        self.logs_path = Path(logs_path)
        self.log_file = self.logs_path / f"watcher_{datetime.now().strftime('%Y%m%d')}.log"

    def on_created(self, event):
        """Called when a file is created in the Drop folder."""
        if event.is_directory:
            return

        source_file = Path(event.src_path)

        # Skip temporary files
        if self.is_temp_file(source_file):
            return

        # Small delay to ensure file is fully written
        time.sleep(1)

        self.log(f"File detected: {source_file.name}")

        # Create action file
        self.create_action_file(source_file)

    def on_moved(self, event):
        """Called when a file is moved in the Drop folder."""
        if event.is_directory:
            return

        source_file = Path(event.dest_path)

        # Skip temporary files
        if self.is_temp_file(source_file):
            return

        self.log(f"File moved: {source_file.name}")

        # Create action file
        self.create_action_file(source_file)

    def is_temp_file(self, file_path):
        """Check if a file is a temporary file."""
        name = file_path.name.lower()
        # Skip temp files, hidden files starting with .
        return (
            name.startswith('.') or
            name.startswith('~') or
            '.tmp' in name or
            name.endswith('.swp') or
            'temp' in name
        )

    def create_action_file(self, source_file):
        """Create an action file in Needs_Action folder."""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        action_file_name = f"action_{timestamp}_{source_file.stem}.md"
        action_file_path = self.needs_action_path / action_file_name

        # Determine file type
        file_ext = source_file.suffix.lower()
        file_type = self.get_file_type(file_ext)

        # Create action file content
        frontmatter = {
            'type': 'file_drop',
            'source': str(source_file.relative_to(self.vault_path)),
            'created': datetime.now().isoformat(),
            'status': 'pending',
            'file_type': file_type
        }

        content = f"""---
{yaml.dump(frontmatter, default_flow_style=False).strip()}
---

# Task: Process {source_file.name}

**Source:** `{source_file.name}`
**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## File Information
- **Path:** `{source_file.relative_to(self.vault_path)}`
- **Type:** {file_type}
- **Size:** {source_file.stat().st_size} bytes

## Instructions
This task requires processing the source file and generating an appropriate response.

---

*Generated by Personal AI Employee Watcher*
"""

        # Write action file
        with open(action_file_path, 'w', encoding='utf-8') as f:
            f.write(content)

        self.log(f"Action file created: {action_file_name}")

    def get_file_type(self, extension):
        """Determine the type of file based on extension."""
        type_map = {
            '.txt': 'text',
            '.md': 'markdown',
            '.pdf': 'document',
            '.doc': 'document',
            '.docx': 'document',
            '.jpg': 'image',
            '.jpeg': 'image',
            '.png': 'image',
            '.gif': 'image',
            '.csv': 'data',
            '.json': 'data',
            '.py': 'code',
            '.js': 'code',
            '.html': 'code',
        }
        return type_map.get(extension, 'unknown')

    def log(self, message):
        """Write log message to log file and print to console."""
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        log_entry = f"[{timestamp}] {message}\n"

        print(log_entry, end='')

        # Ensure log directory exists
        self.logs_path.mkdir(parents=True, exist_ok=True)

        # Write to log file
        with open(self.log_file, 'a', encoding='utf-8') as f:
            f.write(log_entry)


def main():
    """Main entry point for the watcher."""
    # Default vault path
    vault_path = "C:/Users/alvia/OneDrive/Desktop/AI_Employee_Vault_Hackathon"

    # Allow override via command line
    if len(sys.argv) > 1:
        vault_path = sys.argv[1]

    vault_path = Path(vault_path)

    if not vault_path.exists():
        print(f"Error: Vault path does not exist: {vault_path}")
        sys.exit(1)

    # Set up paths
    drop_path = vault_path / "Drop"
    needs_action_path = vault_path / "Needs_Action"
    logs_path = vault_path / "Logs"

    # Create directories if they don't exist
    drop_path.mkdir(parents=True, exist_ok=True)
    needs_action_path.mkdir(parents=True, exist_ok=True)
    logs_path.mkdir(parents=True, exist_ok=True)

    print(f"Starting watcher...")
    print(f"Vault: {vault_path}")
    print(f"Watching: {drop_path}")
    print(f"Actions: {needs_action_path}")
    print(f"Logs: {logs_path}")
    print("-" * 50)

    # Create event handler
    event_handler = DropEventHandler(vault_path, needs_action_path, logs_path)

    # Create observer
    observer = Observer()
    observer.schedule(event_handler, str(drop_path), recursive=False)

    # Start observer
    observer.start()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\nStopping watcher...")
        observer.stop()

    observer.join()
    print("Watcher stopped.")


if __name__ == "__main__":
    main()
